### PR TITLE
Resolve missing scope when compiling grammar outside of src folder

### LINKED ISSUE #14: Cannot find module 'antlr4/index'
If I try to use the lib to compile a grammar outside of the source folder (e.g. on the Desktop), I'm receiving the following exception:

```
{ Error: Cannot find module 'antlr4/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._resolveFilename (…/node_modules/tsconfig-paths/lib/register.js:73:40)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at sandbox.require.id (…/node_modules/node-eval/index.js:61:48)
    ***at Object.<anonymous> (…/Desktop/eval.js:3:14)*** 
    at _commonjsEval (…/node_modules/node-eval/index.js:80:21)
    at module.exports (…/node_modules/node-eval/index.js:36:19)
    at Object.readParser (…/node_modules/antlr4-tool/src/antlr-core/parser-util.ts:20:20)
    at AntlrCompiler.compileTypeScript (…/node_modules/antlr4-tool/src/antlr-core/antlr-compiler.ts:83:37)
    at …/node_modules/antlr4-tool/src/antlr-core/index.ts:48:63
    at …/node_modules/antlr4-tool/src/antlr-core/index.ts:20:25
    at arrayEach (…/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (…/node_modules/lodash/lodash.js:9344:14)
    at compileWithFunction (…/node_modules/antlr4-tool/src/antlr-core/index.ts:10:7)
    at compileGrammarAsTypeScript (…/node_modules/antlr4-tool/src/antlr-core/index.ts:48:12)
```

### PR DESCRIPTION
**Pull request by Patrick-Remy**
Create context and use vm.runInContext instead of eval to prevent require() module not found exception

### CODE REVIEW

**Comment by Patrick-Remy** [comment]
Fixes #14

**Comment by mcchatman8009** [comment]
@Patrick-Remy The fix does not appear to work for TypeScript. Only when the source language is JavaScript is when the code is correclty generated.

`antlr4-tool -l ts ./samples/c/C.g4` does not seem to work. The vmContext doesn't seem able to find the Listener of any choosen Grammar. 

`
Error: Cannot find module './CListener'
`

Also I noticed that if you run the `npm run build`  command, the build fails due to linting errors.

Thanks again for the contributions. I'll be sure to look into you're issues and add a contribution guide that better outlines how to contribute, so that build issues can be better resolved. 

Thanks,

**Comment by mcchatman8009** [comment]
I'll also add some better tests, that can catch these issues. Once I'm able.

**Comment by Patrick-Remy** [comment]
Linting errors, and require issues are resolved. The require function is now more strict and it's paths are limited to the output file's basepath, if the required module isn't antlr4. Another solution could be to just append the basepath to the global paths, e.g. 

```typescript
const vmRequire = (request: string) => require.resolve(request, { paths: [path.dirname(parserFile), ...require.main.paths] });
```

**Comment by mcchatman8009** [comment]
The changes look great @Patrick-Remy. I'm proceeding to merge. Thanks again!

**Pull request merged**
